// Layout only: no terminal authority, credentials or transport.
export const shellMarkup = `
<aside><div class="brand"><b class="mark">●</b> DOT <span>TERMINAL</span></div>
<div class="workspace">PERSONAL WORKSPACE <span class="online">●</span></div>
<button id="new" class="primary">＋ New terminal <kbd>⌘ N</kbd></button>
<div class="section">DOT SESSIONS <button id="refresh" aria-label="Refresh sessions">↻</button></div><nav id="sessions"></nav>
<div class="section">CONNECTED APPS <span>LOCAL</span></div><button id="iterm">▣ iTerm sessions</button><nav id="iterm-list"></nav>
<section id="plan" aria-label="Project plan" data-state="loading"></section>
<div class="bottom"><div class="identity">◈ <div>This Mac<small>Local session owner</small></div><i></i></div><p>Your shells keep running when this window closes.</p></div></aside>
<main><header><button id="menu" aria-label="Toggle sessions" aria-expanded="false">☰</button><div><span class="eyebrow">ONE SESSION. ANY SCREEN.</span><h1 id="title">Your command center</h1></div><div class="header-actions"><button id="appearance" aria-label="Appearance" title="Appearance">◐</button><button id="activity" aria-label="Session activity" title="Session activity" aria-controls="trajectory" aria-expanded="false" class="labelled"><span aria-hidden="true">≡</span> Activity</button><button id="system" aria-label="System and session signals" title="System and session signals">◉</button><button id="browser" aria-label="Open in browser" title="Open in browser">↗</button><button id="control">Take control</button><button id="detach">Release</button></div></header>
<div class="infobar"><span id="state" role="status" aria-live="polite">Choose a session or start a new shell</span><span id="presence" aria-label="Views on this session"></span><span id="input-state" data-state="view-only" aria-live="polite">VIEW ONLY</span><span id="mode">LOCAL · PRIVATE</span></div>
<div class="view-tabs" role="tablist" aria-label="Workspace view" hidden><button role="tab" data-view="terminal" aria-selected="true" aria-controls="terminal">Terminal</button><button role="tab" data-view="activity" aria-selected="false" aria-controls="trajectory" tabindex="-1">Activity</button></div>
<div id="workspace" data-view="terminal"><div id="terminal"><div id="welcome"><div class="orb">●</div><h2>A home for your work.</h2><p>Persistent shells. Connected devices.<br>Pick up exactly where you left off.</p><button id="start">Start a terminal →</button><small>Existing iTerm sessions are available in the sidebar.</small></div></div></div>
<footer><span id="details">DOT / development preview</span><span class="footer-tools"><button id="version" aria-label="Interface version. Reload this view" title="Reload this view"><span id="version-text">build unknown</span> <span aria-hidden="true">⟳</span></button><button id="sync" aria-label="Session synchronization details">Sync · unknown</button></span></footer></main>`;
